routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DishController@index');

// Profile routes
Route::get('/profile', 'UserController@profile')->name('profile')->middleware('auth');
Route::put('/profile', 'UserController@update')->name('profile.update')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('contacts', 'ContactController');

Route::resource('dishes', 'DishController');

Route::resource('orders', 'OrderController');


Route::delete('orders/delete-line/{lineId}', 'OrderController@destroyLine')->name('orders.destroyLine');

Route::post('orders/add-line/{orderId}', 'OrderController@addLine')->name('orders.addLine');


Route::resource('tables', 'TableController');

Route::resource('users', 'UserController');

Route::get('/profile', 'UserController@profile')->name('profile');

Route::post('cart', 'OrderController@addToCart')->name('cart.add');

Route::delete('cart', 'OrderController@ClearCart')->name('cart.clear');

Route::get('/checkout', 'OrderController@CartCheckout')->name('cart.checkout')->middleware('auth');

Route::get('cart/delete/{id}', 'OrderController@cartDeleteRow')->name('cart.deleteRow');

Route::get('/reservationinfo', 'CheckoutController@ReservationInfo')->name('cart.reservationinfo');

Route::post('/reservationconfirmation', 'CheckoutController@ReservationConfirmation')->name('cart.reservationconfirmation');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'surname','email', 'password', 'birthdate', 'phone', 'city', 'country', 'address', 'zipcode'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function orders(){
    return $this->hasMany('\App\Order');
}

public function isAdmin()
{
  return $this->type === 'admin';
}

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Order;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

     public function __construct() {
             $this->middleware('authAdmin')
                  ->except(['profile', 'update']);

             $this->middleware('auth');
         }

         public function index()
         {
           $users = User::all();
           return view('users.index', compact('users'));
         }

      public function profile()
      {
          $user = \Auth::user();
          $title = 'Update profile';
          return view('auth.register', compact('user', 'title'));
      }

      public function update(Request $request, User $user)
      {
          $user = \Auth::user();

          $user->name = $request->name;
          $user->surname = $request->surname;
          $user->birthdate = $request->birthdate;
          $user->phone = $request->phone;
          $user->city = $request->city;
          $user->address = $request->address;
          $user->country = $request->country;
          $user->zipcode = $request->zipcode;
          $user->save();

          return redirect()->route('dishes.index')->with('message', [
              'text' => 'Profile updated!',
              'type' => 'success'
          ]);
      }

      public function show(User $user)
      {
        return view('users.show', compact('user'));
      }

      public function edit(User $user)
      {
        // $title = 'Update profile';
        // return view('auth.register', compact('user', 'title'));
      }

      public function destroy(User $user)
      {
        foreach ($user->orders as $order) {
        $order->delete();
        }
        $user->delete();
        return redirect()->route('users.index');
      }

}

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <h1>Users list</h1>
        <table class="table table-bordered table-hover">
	<thead>
		<tr>
			<th>
				Actions
			</th>
			<th>
				Name
			</th>
			<th>
				Surname
			</th>
      <th>
        Phone
      </th>
			<th>
				Email
			</th>
      <th>
        Date of birth
      </th>
			<th>
				Type
			</th>
		</tr>
	</thead>
	<tbody>
    @foreach ($users as $user)
      <tr>
        <td class="">
            @if (Auth::check() && Auth::user()->isAdmin())

              <div class="btn-group">
                <a class="btn btn-sm btn-default" href="{{ route('users.show', ['id' => $user->id]) }}">Show</a>
                {!! Form::open([
                  'route' => ['users.destroy', $user->id],
                  'method' =>'delete',
                  'id'=> 'order-id'.$user->id,
                  'class'=>'btn-group'
                  ]) !!}
                  {!!Form::submit('X',['class' => 'btn btn-sm btn-danger'])!!}

                  {!! Form::close() !!}
                </div>
            @else
              <div class="btn-group">
                <a class="btn btn-sm btn-default" href="{{ route('orders.show', ['id' => $order->id]) }}">Show</a>
                </div>
            @endif

        </td>
        <td>
          {{ $user->name }}
        </td>
        <td>
          {{ $user->surname }}
        </td>
        <td>
          {{ $user->phone }}
        </td>
        <td>
          {{ $user->email }}
        </td>
        <td>
          {{ $user->birthdate }}
        </td>
        <td>
          <span class="label label-pill label-primary">{{ ucfirst($user->type) }}</span>
        </td>
      </tr>
    @endforeach
	</tbody>
</table>
      </div>
    </div>
  </div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div class="row">
          <div class="col-md-6">
            <h3>User: {{$user->name}} {{ $user->surname }}</h3>
            <h3>Email: <a href= "mailto:{{$user->email}}">{{$user->email}}</a></h3>
            <h3>Phone: {{$user->phone}}</h3>
          </div>
          <div class="col-md-6">
            <h3>Country: {{$user->country}}</h3>
            <h3>City: {{$user->city}}</h3>
            <h3>Address: {{$user->address}}</h3>
            <h3>Zip code: {{$user->zipcode}}</h3>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <h2>Orders</h2>
            <div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">All orders</a></li>

  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="allorders">
      <table class="table table-bordered">
<thead>
  <tr>
    <th>
      Actions
    </th>
    <th>
      Name
    </th>
    <th>
      Email
    </th>
    <th>
      Total
    </th>
    <th>
      Reservation date
    </th>
  </tr>
</thead>
<tbody>
  @foreach ($user->orders as $order)
    <tr class="{{$order->getOrderStatus()}}">
      <td class="table-edit">
          @if (Auth::check() && Auth::user()->isAdmin())

            <div class="btn-group">
              <a class="btn btn-sm btn-default" href="{{ route('orders.show', ['id' => $order->id]) }}">Show</a>
              <a class="btn btn-sm btn-success" href="{{ route('orders.edit', ['id' => $order->id]) }}">Edit</a>
              {!! Form::open([
                'route' => ['orders.destroy', $order->id],
                'method' =>'delete',
                'id'=> 'order-id'.$order->id,
                'class'=>'btn-group'
                ]) !!}
                {!!Form::submit('X',['class' => 'btn btn-sm btn-danger'])!!}

                {!! Form::close() !!}
              </div>
          @else
            <div class="btn-group">
              <a class="btn btn-sm btn-default" href="{{ route('orders.show', ['id' => $order->id]) }}">Show</a>
              </div>
          @endif

      </td>
      <td>
        {{ $order->client_name }}
      </td>
      <td>
        {{ $order->client_email }}
      </td>
      <td>
        {{ $order->total }}
      </td>
      <td>
        {{ $order->reservation_date }}
      </td>
    </tr>
  @endforeach
</tbody>
</table>
  </div>

  </div>

</div>
          </div>
        </div>
        {{-- <h1>Order number: {{$order->id}} </h1>
        <h2>Client: {{$order->client_name}} </h2>
        <h2>Table: {{$order->table->title}} </h2>
        <h2>Number of persons: {{$order->number_of_persons}} </h2>
        <h2>Reservation time: {{$order->reservation_date}}  {{$order->reservation_time}}</h2>
        <h1>Ordered dishes:</h1>
            <table class="table table-bordered table-responsive checkout-table">
              <thead>
                <tr>
                  <th>
                    Photo
                  </th>
                  <th>
                    Title
                  </th>
                  <th>
                    Price
                  </th>
                  <th>
                    Quantity
                  </th>
                  <th>
                    Total
                  </th>
                </tr>
              </thead>
              <tbody>
                @foreach ($order->order_lines as $item)
                <tr>
                  <td>
                    <img class="img-responsive" src="{{$item->dish->photo}}" alt="{{$item->dish->title}}">
                  </td>
                  <td>
                    {{$item->dish->title}}
                  </td>
                  <td>
                    {{$item->dish->price}} &euro;
                  </td>
                  <td>
                    {{$item->quantity}}
                  </td>
                  <td>
                    {{$item['total']}} &euro;
                  </td>
                </tr>
                @endforeach
              </tr>
                <td>
                </td>
                <td>
                </td>
                <td>
                </td>
                <td>
                  Total:
                </td>
                <td>
                  {{$order->total}} &euro;
                </td>
              </tr>
              </tbody>
            </table> --}}
      </div>
    </div>
  </div>
@endsection