routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DishController@index');

// Profile routes
Route::get('/profile', 'UserController@profile')->name('profile')->middleware('auth');
Route::put('/profile', 'UserController@update')->name('profile.update')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('contacts', 'ContactController');

Route::resource('dishes', 'DishController');

Route::resource('orders', 'OrderController');


Route::delete('orders/delete-line/{lineId}', 'OrderController@destroyLine')->name('orders.destroyLine');

Route::post('orders/add-line/{orderId}', 'OrderController@addLine')->name('orders.addLine');


Route::resource('tables', 'TableController');

Route::resource('users', 'UserController');

Route::get('/profile', 'UserController@profile')->name('profile');

Route::post('cart', 'OrderController@addToCart')->name('cart.add');

Route::delete('cart', 'OrderController@ClearCart')->name('cart.clear');

Route::get('/checkout', 'OrderController@CartCheckout')->name('cart.checkout')->middleware('auth');

Route::get('cart/delete/{id}', 'OrderController@cartDeleteRow')->name('cart.deleteRow');

Route::get('/reservationinfo', 'CheckoutController@ReservationInfo')->name('cart.reservationinfo');

Route::post('/reservationconfirmation', 'CheckoutController@ReservationConfirmation')->name('cart.reservationconfirmation');

app/Http/Controllers/TableController.php
<?php

namespace App\Http\Controllers;

use App\Table;
use Illuminate\Http\Request;

class TableController extends Controller
{


  public function __construct() {
          $this->middleware('authAdmin')
               ->except(['index']);

      }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $tables = Table::all();
      return view('tables.index', compact('tables'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tables.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $timestamps = false;
      $table = new Table();
      $table->title = $request->title;
      $table->min = $request->min;
      $table->max = $request->max;
      $table->photo='http://placehold.it/300';

      $table->save();
      return redirect()->route('tables.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Table  $table
     * @return \Illuminate\Http\Response
     */
    public function show(Table $table)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Table  $table
     * @return \Illuminate\Http\Response
     */
    public function edit(Table $table)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Table  $table
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Table $table)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Table  $table
     * @return \Illuminate\Http\Response
     */
    public function destroy(Table $table)
    {
        //
    }
}

resources/views/tables/form.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    @if (isset($dish))
      <h1>Table edit</h1>
    @else
      <h1>Table create</h1>
    @endif
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div class="row">
          @if (isset($table))
            <div class="col-md-4">
              <img style="margin: 0 auto;" class="img-responsive" src="{{$table->photo}}?text={{$table->title}}" alt="{{$table->title}}">
            </div>
          @endif
          <div class="col-md-8">
            @if (isset($table))
              {!! Form::model($table, ['route' => ['tables.update', $table->id],'method' => 'put']) !!}
            @else
              {!! Form::open([
                'route' => 'tables.store',
                'method' =>'post'
                ]) !!}
              @endif
              <div class="form-group">
                <label for="title">Table title:</label>
                {!!Form::text('title',null,['class'=>"form-control",'placeholder'=>'Title'])!!}

                <label for="netto_price">Min persons:</label>
                {!!Form::number('min',null,['class'=>"form-control",])!!}

                <label for="max">Max persons:</label>
                {!!Form::number('max',null,['class'=>"form-control",])!!}
              </div>
              <div class="btn-group">
                @if (isset($table))
                  <a class="btn btn-default" href="{{ route('tables.index') }}">Back to tables</a>
                  {!!Form::submit('Save',['class' => 'btn btn-primary'])!!}
                  {!! Form::close() !!}
                @else
                  {!!Form::submit('Submit',['class' => 'btn btn-primary'])!!}
                  {!! Form::close() !!}
                @endif
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  @endsection

resources/views/tables/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
      <div class="btn-group">
      </div>
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        @if (Auth::check() && Auth::user()->isAdmin())
          <a class="" href="{{ route('tables.create') }}">
            <p>+ Create table</p>
            </a>
          @endif
        @foreach ($tables as $table)
          <div class="row table">
            <div class="col-md-4">
              <img class="img-responsive" src="{{$table->photo}}?text={{$table->title}}" alt="{{$table->title}}">
            </div>
            <div class="col-md-8">
              <h1>Table: {{$table->title}}</h1>
              <h2>Min persons: {{$table->min}}</h2>
              <h2>Max persons: {{$table->max}}</h2>

            </div>
          </div><br>
        @endforeach
      </div>
    </div>
  </div>
@endsection

resources/views/tables/show.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div class="row">
          <div class="col-md-4">
            <img style="margin: 0 auto;" class="img-responsive" src="{{$dish->photo}}?text={{$dish->title}}" alt="{{$dish->title}}">
          </div>
          <div class="col-md-8">
            <h1>{{$dish->title}}</h1>
            <p>{{$dish->description}}</p>
            <p>Kaina: {{$dish->FormatedPrice}} EUR</p>
            <p>Kiekis: {{$dish->quantity}} vnt.</p>
            <div class="btn-group">
              <a class="btn btn-primary" href="{{ route('dishes.index') }}">Back to dishes</a>
              @if (Auth::check())
                <a class="btn btn-success" href="{{ route('dishes.edit', ['id' => $dish->id]) }}">Edit</a>
                {!! Form::open([
                  'route' => ['dishes.destroy', $dish->id],
                  'method' =>'delete',
                  'class'=> 'btn-group'
                  ]) !!}
                  {!!Form::submit('Delete',['class' => 'btn btn-danger'])!!}

                  {!! Form::close() !!}
              @endif
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection