routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DishController@index');

// Profile routes
Route::get('/profile', 'UserController@profile')->name('profile')->middleware('auth');
Route::put('/profile', 'UserController@update')->name('profile.update')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('contacts', 'ContactController');

Route::resource('dishes', 'DishController');

Route::resource('orders', 'OrderController');


Route::delete('orders/delete-line/{lineId}', 'OrderController@destroyLine')->name('orders.destroyLine');

Route::post('orders/add-line/{orderId}', 'OrderController@addLine')->name('orders.addLine');


Route::resource('tables', 'TableController');

Route::resource('users', 'UserController');

Route::get('/profile', 'UserController@profile')->name('profile');

Route::post('cart', 'OrderController@addToCart')->name('cart.add');

Route::delete('cart', 'OrderController@ClearCart')->name('cart.clear');

Route::get('/checkout', 'OrderController@CartCheckout')->name('cart.checkout')->middleware('auth');

Route::get('cart/delete/{id}', 'OrderController@cartDeleteRow')->name('cart.deleteRow');

Route::get('/reservationinfo', 'CheckoutController@ReservationInfo')->name('cart.reservationinfo');

Route::post('/reservationconfirmation', 'CheckoutController@ReservationConfirmation')->name('cart.reservationconfirmation');

app/Dish.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Dish extends Model
{
//     public function getFormatedPriceAttribute(){
//       return number_format($this->price/100,2);
// }
//
// public function getNettoPriceAttribute($value){
//   return number_format($value/100,2);
// }

public function order_lines() {
  return $this->hasMany('\App\OrderLine');
}

public function getNetto(){
return $this->price/1.21;
}
}

app/Http/Controllers/DishController.php
<?php

namespace App\Http\Controllers;

use App\Dish;
use Illuminate\Http\Request;

class DishController extends Controller
{

  // public function __construct() {
  //   $this->middleware('auth',
  //   ['except'=>['index','show']]
  // );
  // }

  public function __construct() {
          $this->middleware('authAdmin')
               ->except(['index', 'show']);
      }


  /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function index()
  {
    $dishes = Dish::all();
    return view('dishes.index', compact('dishes'));
  }

  /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function create()
  {
    return view('dishes.form');
  }

  /**
  * Store a newly created resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @return \Illuminate\Http\Response
  */


  public function store(Request $request)
  {
      $dish = new Dish();
      $dish->title = $request->title;
      $dish->description = $request->description;
      $dish->price = $request->price;
      $dish->netto_price = $request->price/1.21;
      $dish->photo='http://placehold.it/300';
      $dish->quantity = $request->quantity;

      $dish->save();
      return redirect()->route('dishes.index');
  }

  /**
  * Display the specified resource.
  *
  * @param  \App\Dish  $dish
  * @return \Illuminate\Http\Response
  */
  public function show(Dish $dish)
  {
    return view('dishes.show', compact('dish'));
  }

  /**
  * Show the form for editing the specified resource.
  *
  * @param  \App\Dish  $dish
  * @return \Illuminate\Http\Response
  */
  public function edit(Dish $dish)
  {
    return view('dishes.form', compact('dish'));
  }

  /**
  * Update the specified resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @param  \App\Dish  $dish
  * @return \Illuminate\Http\Response
  */
  public function update(Request $request, Dish $dish)
  {
    $dish->title = $request->title;
    $dish->description = $request->description;
    $dish->price = $request->price;
    $dish->netto_price = $request->price/1.21;
    $dish->quantity = $request->quantity;

    $dish->update();
    return redirect()->route('dishes.index');
  }

  /**
  * Remove the specified resource from storage.
  *
  * @param  \App\Dish  $dish
  * @return \Illuminate\Http\Response
  */
  public function destroy(Dish $dish)
  {
    $dish->delete();
    return redirect()->route('dishes.index');
  }
}

resources/views/dishes/form.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    @if (isset($dish))
      <h1>Dish edit</h1>
    @else
      <h1>Dish create</h1>
    @endif
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div class="row">
          @if (isset($dish))
            <div class="col-md-4">
              <img style="margin: 0 auto;" class="img-responsive" src="{{$dish->photo}}?text={{$dish->title}}" alt="{{$dish->title}}">
            </div>
          @endif
          <div class="col-md-8">
            @if (isset($dish))
              {!! Form::model($dish, ['route' => ['dishes.update', $dish->id],'method' => 'put']) !!}
            @else
              {!! Form::open([
                'route' => 'dishes.store',
                'method' =>'post'
                ]) !!}
              @endif
              <div class="form-group">
                <label for="title">Dish title:</label>
                {!!Form::text('title',null,['class'=>"form-control",'placeholder'=>'Title'])!!}
              </div>

              <div class="form-group">
                <label for="title">Dish description:</label>
                {!!Form::textarea('description',null,['class'=>"form-control",'placeholder'=>'Title'])!!}
              </div>

              <div class="form-group">
                <label for="price">Dish price:</label>
                {!!Form::text('price',null,['class'=>"form-control",])!!}
                <label for="quantity">Dish quantity:</label>
                {!!Form::number('quantity',null,['class'=>"form-control",])!!}
              </div>
              <div class="btn-group">
                @if (isset($dish))
                  <a class="btn btn-default" href="{{ route('dishes.index') }}">Back to dishes</a>
                  {!!Form::submit('Save',['class' => 'btn btn-primary'])!!}
                  {!! Form::close() !!}
                @else
                  {!!Form::submit('Submit',['class' => 'btn btn-primary'])!!}
                  {!! Form::close() !!}
                @endif
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  @endsection

resources/views/dishes/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        @if (Auth::check() && Auth::user()->isAdmin())
          <a class="" href="{{ route('dishes.create') }}">
            <p>+ Create dish</p>
            </a>
          @endif
        @foreach ($dishes as $dish)
          <div class="row dish">
            <div class="col-md-4">
              <a  href="{{ route('dishes.show', ['id' => $dish->id]) }}"><img class="img-responsive" src="{{$dish->photo}}?text={{$dish->title}}" alt="{{$dish->title}}"></a>
            </div>
            <div class="col-md-8">
              <h1>{{$dish->title}}</h1>
              <p>{{$dish->description}}</p>
              <p><strong>Kaina: </strong>{{ number_format($dish->price,2) }} &euro;</p>
              @if (Auth::check())
                <a  class="btn btn-success btn-sm add-to-cart" data-id="{{$dish->id}}"  href="#"><i class="fa fa-cart-plus" aria-hidden="true"></i> Add to cart</a>
              @endif
            </div>
          </div><br>
        @endforeach
      </div>
    </div>
  </div>
@endsection

resources/views/dishes/show.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div class="row">
          <div class="col-md-4">
            <img style="margin: 0 auto;" class="img-responsive" src="{{$dish->photo}}?text={{$dish->title}}" alt="{{$dish->title}}">
          </div>
          <div class="col-md-8">
            <h1>{{$dish->title}}</h1>
            <p>{{$dish->description}}</p>
            <p>Price: {{ number_format($dish->price,2) }} &euro;</p>
            <div class="btn-group">
              <a class="btn btn-primary" href="{{ route('dishes.index') }}">Back to dishes</a>
              @if (Auth::check() && Auth::user()->isAdmin())
                <a class="btn btn-success" href="{{ route('dishes.edit', ['id' => $dish->id]) }}">Edit</a>
                {!! Form::open([
                  'route' => ['dishes.destroy', $dish->id],
                  'method' =>'delete',
                  'class'=> 'btn-group'
                  ]) !!}
                  {!!Form::submit('Delete',['class' => 'btn btn-danger'])!!}

                  {!! Form::close() !!}
              @endif
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection