routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DishController@index');

// Profile routes
Route::get('/profile', 'UserController@profile')->name('profile')->middleware('auth');
Route::put('/profile', 'UserController@update')->name('profile.update')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('contacts', 'ContactController');

Route::resource('dishes', 'DishController');

Route::resource('orders', 'OrderController');


Route::delete('orders/delete-line/{lineId}', 'OrderController@destroyLine')->name('orders.destroyLine');

Route::post('orders/add-line/{orderId}', 'OrderController@addLine')->name('orders.addLine');


Route::resource('tables', 'TableController');

Route::resource('users', 'UserController');

Route::get('/profile', 'UserController@profile')->name('profile');

Route::post('cart', 'OrderController@addToCart')->name('cart.add');

Route::delete('cart', 'OrderController@ClearCart')->name('cart.clear');

Route::get('/checkout', 'OrderController@CartCheckout')->name('cart.checkout')->middleware('auth');

Route::get('cart/delete/{id}', 'OrderController@cartDeleteRow')->name('cart.deleteRow');

Route::get('/reservationinfo', 'CheckoutController@ReservationInfo')->name('cart.reservationinfo');

Route::post('/reservationconfirmation', 'CheckoutController@ReservationConfirmation')->name('cart.reservationconfirmation');

resources/views/layouts/app.blade.php
@php
use App\Contact;
$contact = App\Contact::find(1)->get();
@endphp
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <title>{{ config('app.name', 'Laravel') }}</title>

  <!-- Styles -->
  <link href="{{ asset('css/app.css') }}" rel="stylesheet">

  <!-- Scripts -->
  <script>
  window.Laravel = {!! json_encode([
    'csrfToken' => csrf_token(),
    'cartAddRoute'=> route('cart.add'),
    'cartClearRoute'=> route('cart.clear')
    ]) !!};
    </script>
    <script src="//cloud.tinymce.com/stable/tinymce.min.js"></script>
    <script>tinymce.init({ selector:'#hours' });</script>
  </head>
  <body>
    <div id="app">
      <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
          <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
              <span class="sr-only">Toggle Navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="{{ url('/') }}">
              {{ isset($contact) ? $contact[0]->title : config('app.name', 'Laravel') }}
            </a>
          </div>

          <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <!-- Left Side Of Navbar -->
            @if (Auth::check())
              <ul id="cart-menu" class="nav navbar-nav">
                &nbsp;
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                    <i class="fa fa-shopping-cart" aria-hidden="true"></i> Cart <span class="caret"></span>
                  </a>

                  <ul id="cart-items" class="dropdown-menu" role="menu">
                    @if (session('cart.items') && count(session('cart.items'))>0)
                      @foreach (session('cart.items') as $item)
                        <li>
                          <a href="#">{{$item['title']}} x {{$item['quantity']}} = {{ $item['total'] }} &euro;</a>
                        </li>
                      @endforeach
                    @endif
                  </ul>
                </li>

                <li><a href="#">Total: <span id="grand_total">{{session('cart.total') ?: '0'}}</span> EUR</a></li>
                <li><a class="clear-cart"  href="#" ><i class="fa fa-trash" aria-hidden="true"></i> Clear cart</a></li>
                <li><a   href="{{ route('cart.checkout') }}" ><i class="fa fa-credit-card" aria-hidden="true"></i> Checkout</a></li>

              </ul>
            @endif

            <!-- Right Side Of Navbar -->
            <ul class="nav navbar-nav navbar-right">
              <!-- Authentication Links -->
              @if (Auth::guest())
                <li><a href="{{ route('login') }}">Login</a></li>
                <li><a href="{{ route('register') }}">Register</a></li>
              @else
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                    <i class="fa fa-user-o" aria-hidden="true"></i> {{ Auth::user()->name }} <span class="caret"></span>
                  </a>

                  <ul class="dropdown-menu" role="menu">
                    @if (Auth::check() && Auth::user()->isAdmin())

                      <li><a class="" href="{{ route('profile') }}">
                        <p>Profile</p>
                      </a></li>
                      <li><a class="" href="{{ route('users.index') }}">
                        <p>Users list</p>
                      </a></li>
                      <li><a class="" href="{{ route('dishes.index') }}">
                        <p>Dishes</p>
                      </a></li>
                      <li><a class="" href="{{ route('orders.index') }}">
                        <p>Orders</p>
                      </a></li>
                      <li><a class="" href="{{ route('tables.index') }}">
                        <p>Tables</p>
                      </a></li>
                      <li>
                        <a href="{{ route('logout') }}"
                        onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
                        Logout
                      </a>

                      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                      </form>
                    </li>
                    @else
                      <li><a class="" href="{{ route('profile') }}">
                        <p>Profile</p>
                      </a></li>
                      <li><a class="" href="{{ route('dishes.index') }}">
                        <p>Dishes</p>
                      </a></li>
                      <li><a class="" href="{{ route('orders.index') }}">
                        <p>Orders</p>
                      </a></li>
                      <li>
                        <a href="{{ route('logout') }}"
                        onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
                        Logout
                      </a>

                      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                      </form>
                    </li>
                    @endif
                </ul>
              </li>
            @endif
          </ul>
        </div>
      </div>
    </nav>
    @if (session('message'))
      <div class="alert alert-{{session('message')['type']}}">
        {{session('message')['text']}}
      </div>
    @endif
    @yield('content')
    <footer class="footer navbar-fixed-bottom">

      <p><a class="" href="{{ route('contacts.index')}}">
        <i class="fa fa-envelope-o" aria-hidden="true"></i> Contacts
      </a></p>

    </footer>
  </div>

  <!-- Scripts -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-formhelpers/2.3.0/js/bootstrap-formhelpers.min.js" integrity="sha256-H7Mu9l17V/M6Q1gDKdv27je+tbS2QnKmoNcFypq/NIQ=" crossorigin="anonymous"></script>
  <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/checkout.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <h1>CHECKOUT</h1>

        @if (session('cart.items') && count(session('cart.items'))>0)
        <table class="table table-bordered table-responsive table-condensed checkout-table">
          <thead>
            <tr>
              <th>
                Delete
              </th>
              <th>
                Photo
              </th>
              <th>
                Title
              </th>
              <th>
                Price
              </th>
              <th>
                Netto price
              </th>
              <th>
                Quantity
              </th>
              <th>
                Netto total
              </th>
              <th>
                Total
              </th>
            </tr>
          </thead>
          <tbody>
            @foreach (session('cart.items') as $item)
            <tr>
              <td>
                <a  href="{{route('cart.deleteRow', ['id' =>$item['id']])}}" class="btn btn-danger btn-sm deleteRow" data-id="{{$item['id']}}" href="#">X</a>
              </td>
              <td>
                <img class="img-responsive" src="{{$item['photo']}}" alt="{$item['title']}}">
              </td>
              <td>
                {{$item['title']}}
              </td>
              <td>
                {{ number_format($item['price'], 2)}} &euro;
              </td>
              <td>
                {{ number_format($item['netto_price'],2)}} &euro;
              </td>
              <td>
                {{$item['quantity']}}
              </td>
              <td>
                {{number_format($item['total']/1.21,2)}} &euro;
              </td>
              <td>
                {{number_format($item['total'],2)}} &euro;
              </td>
            </tr>
            @endforeach
          </tr>
          <td colspan="6">
          </td>
          <td>
            Netto total:
          </td>
          <td>
            {{ number_format(session('cart.totalNetto'),2) }} &euro;
          </td>
        </tr>
          </tr>
          <td colspan="6">
          </td>

            <td>
              VAT 21%: 
            </td>
            <td>
              {{ number_format(session('cart.total')-session('cart.totalNetto'),2) }} &euro;
            </td>
          </tr>
        </tr>
          </tr>
          <td colspan="6">
          </td>
            <td>
              Total:
            </td>
            <td>
              {{ number_format(session('cart.total'),2) }} &euro;
            </td>
          </tr>
          </tbody>
        </table>
        <div class="btn-group pull-right">
          <a class="btn btn-danger clear-cart" href="#" >Clear cart</a>
          <a href="{{ route('cart.reservationinfo') }}" class="btn btn-success" href="#">Next</a>
        </div>
        @endif
      </div>
      </div>

  </div>
@endsection

resources/views/layouts/checkoutform.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    @if (isset($order))
      <h1>Order edit</h1>
    @else
      <h1>Reservation info</h1>
    @endif
    @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div class="row">
          <div class="col-md-8">
            @if (isset($order))
              {!! Form::model($order, ['route' => ['orders.update', $order->id],'method' => 'put']) !!}
            @else
              {!! Form::open([
                'route' => 'cart.reservationconfirmation',
                'method' =>'post'
                ]) !!}
              @endif
              <div class="form-group">
                <label for="client_name">Client name:</label>
                {!!Form::text('client_name', Auth::user() ? Auth::user()->name : null, ['class'=>"form-control",'placeholder'=>'Name'])!!}
              </div>

              <div class="form-group">
                <label for="client_email">Client email:</label>
                {!!Form::email('client_email',Auth::user() ? Auth::user()->email : null,['class'=>"form-control",'placeholder'=>'Email'])!!}
              </div>
              <div class="form-group">
                <label for="client_phone">Client phone:</label>
                {!!Form::text('client_phone',Auth::user() ? Auth::user()->phone : null,['class'=>"form-control",'placeholder'=>'Email'])!!}
              </div>
              <div class="form-group">
                <label for="persons">How many persons?:</label>
                {!!Form::selectRange('persons', 1, 8);!!}
              </div>
              <div class="form-group">
                <label for="table">Please select table:</label>
                {!!Form::select('table',$tables,null,['class'=>"form-control"])!!}
              </div>
              <div class="form-group">
                <label for="date">Please select date:</label>
                {!!Form::date('date',null,['class'=>"form-control"])!!}
              </div>
              <div class="form-group">
                <label for="time">Please select time:</label>
                {!!Form::time('time',null,['class'=>"form-control"])!!}
              </div>

              @if (session('cart.total'))
                <p>Total: {{session('cart.total')}} &euro;</p>
              @endif
              <div class="btn-group">
                @if (isset($order))
                  <a class="btn btn-default" href="{{ route('orders.index') }}">Back to orders</a>
                  {!!Form::submit('Save',['class' => 'btn btn-primary'])!!}
                  {!! Form::close() !!}
                @else
                  {!!Form::submit('Confirm reservation',['class' => 'btn btn-primary'])!!}
                  {!! Form::close() !!}
                @endif
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  @endsection

resources/views/layouts/reservationconfirmation.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div class="row">
          <div class="col-md-6">
            <h1>Client: {{session('reservation')['client_name']}}</h1>
            <h3>Email: {{session('reservation')['client_email']}}</h3>
            <h3>Phone: {{session('reservation')['client_phone']}}</h3>
            <h3>Table: {{session('reservation')['table']}}</h3>
            <h3>Date: {{session('reservation')['date']}} {{session('reservation')['time']}}</h3>
          </div>
          <div class="col-md-6">
            <h2>Ordered dishes:</h2>
            <ul class="list-unstyled">
              @foreach (session('cart.items') as $item)
                <h3><li>{{$item['title']}} - {{$item['quantity']}} pcs. x {{$item['price']}} &euro; =  {{$item['total']}} &euro;</li></h3>
              @endforeach
            </ul>
            <h2>Order total: {{session('cart.total')}} &euro;</h2>
          </div>
        </div>
        {!! Form::open([
          'route' => 'orders.store',
          'method' =>'post'
          ]) !!}
          {!!Form::submit('Place order',['class' => 'btn btn-primary'])!!}
          {!! Form::close() !!}
      </div>
    </div>
  </div>
@endsection